**Welcome to numpy**

In [2]:
import numpy as np

In [3]:
myarr=np.array([[3,4,502,6]],np.int64)

In [4]:
myarr[0,2]

502

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [13]:
myarr[0,2]=45

In [15]:
myarr

array([[ 3,  4, 45,  6]], dtype=int64)

**Conversion from other python structures**

In [19]:
listarray=np.array([[1,2,3],[5,6,7],[0,3,1]])

In [21]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 3, 1]])

In [23]:
listarray.dtype

dtype('int32')

In [25]:
listarray.size

9

In [27]:
listarray.shape

(3, 3)

In [29]:
np.array({34,23,16})

array({16, 34, 23}, dtype=object)

In [35]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
rng=np.arange(15)

In [39]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
lspace=np.linspace(1,5,12)

In [43]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [47]:
emp = np.empty((4,6))

emp

In [50]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23058707e-307, 8.45593934e-307, 7.56593017e-307],
       [1.11258854e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307, 6.23059726e-307, 8.90104239e-307],
       [6.89804133e-307, 1.69118923e-306, 1.33511562e-306,
        6.23061084e-307, 1.60219306e-306, 1.78019082e-306],
       [1.69120552e-306, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [52]:
emp_like=np.empty_like(lspace)

In [54]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [56]:
arr=np.arange(99)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [64]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [66]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [74]:
ar=np.array(x)

In [70]:
ar.sum(axis=0)

array([12,  8,  9])

In [72]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [76]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar.flat

In [86]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [88]:
ar.ndim

2

In [90]:
ar.nbytes

36

In [92]:
ar.size

9

In [94]:
one=np.array([1,2,3,4,5])

In [96]:
one.argmax()

4

In [98]:
one.argmin()

0

In [100]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [102]:
one[2]=5

In [104]:
one

array([1, 2, 5, 4, 5])

In [106]:
one.argsort()

array([0, 1, 3, 2, 4], dtype=int64)